#!/usr/bin/env bash
# Script used in pin images, used in publish workflow.
set -euo pipefail

# parse arguments.
version="$1" registry="$2" digest_dir="$3"

# check hash is a hash
check_digest() {
    [[ "$2" =~ ^sha256:[0-9a-f]{64}$ ]] || { echo "Bad digest for $1: '$2'" >&2; exit 1; }
}

# make sure we have .env for docker compose
[ -f .env ] || touch .env

# parse docker compose
config=$(docker compose -f docker-compose.yaml config --no-interpolate --format json)
# get services
services=$(jq -r '.services | to_entries[] | [.key, .value.image] | @tsv' <<< "$config")
# make sure we have services
[ -n "$services" ] || { echo "No services found in docker-compose.yaml" >&2; exit 1; }

# empty dict to store image and digest.
declare -A pinned

# now do the pinning, echoing to stdout
echo "# wis2downloader ${version} images, generated by the release workflow"
echo "services:"
while IFS=$'\t' read -r service image; do
    echo "  ${service}:"
    if [[ "$image" == wis2downloader-* ]]; then # wis2 downloader image
        digest=$(< "${digest_dir}/${image#wis2downloader-}.digest")
        check_digest "$image" "$digest"
        echo "    image: ${registry}/${image}:${version}@${digest}"
        echo "    build: !reset null"
    else # external images
        if [ -z "${pinned[$image]:-}" ]; then
            digest=$(docker buildx imagetools inspect "$image" --format '{{json .Manifest}}' | jq -r .digest)
            check_digest "$image" "$digest"
            pinned[$image]="${image}@${digest}"
        fi
        echo "    image: ${pinned[$image]}"
    fi
done <<< "$services"
